apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: parity-dev
  name: parity-dev
spec:
  ports:
  - name: "8180"
    port: 8180
    targetPort: 8180
  - name: "8545"
    port: 8545
    targetPort: 8545
  - name: "30303"
    port: 30303
    targetPort: 30303
  selector:
    io.kompose.service: parity-dev
  type: LoadBalancer
status:
  loadBalancer: {}
